### ISSUE TITLE
Consider using byte positions for source locations internally

### ISSUE THREAD

**Issue by brendanzab** [Marwes/gluon#108]
Rather than keeping the row and column information from lexing onwards, rustc and LALRPOP use byte positions for source locations internally. They then reconstruct row and column information later. Not sure what all the the pros and cons are, but here are some:

- slightly less memory used in AST
- easier to integrate with LALRPOP

Maybe @nikomatsakis can weigh in on some of the reasoning behind this?

- `libsyntax_pos`: https://github.com/rust-lang/rust/blob/ae774103501337ed63b42b673c6c4fdbf369e80e/src/libsyntax_pos/lib.rs
- `lalrpop::file_text`: https://github.com/nikomatsakis/lalrpop/blob/125cf975e36cca84b18c7faf0b9187e7d46c5a6d/lalrpop/src/file_text.rs

**Comment by brendanzab** [comment]
We might have to weigh up the fact the gluon is intended to be embeddable, but I'm not sure whether this would have an impact or not.

**Comment by nikomatsakis** [comment]
If you are writing your own lexer, LALRPOP can handle custom location types, no problem. So I think that LALRPOP integration is not really an important factor.

However,  I do like using the byte-offset nonetheless. As you say, it's more compact in memory, which is the most important consideration. It's also perfectly general, simple, and it allows you to do things like easily find the original source text from a given span. The downside is that you need some context to convert to a line-column, but I tend to find that printing errors needs context anyhow.

**Comment by Marwes** [comment]
With line + column there is still the reverse problem as then one needs to calculate the byte positions for each line https://github.com/Marwes/gluon/blob/4a64c68d8d04a6788f1fea3d6f25471b873ee8e2/base/src/error.rs#L74.

Thus the only real problem is that the [errors in the typechecker](https://github.com/Marwes/gluon/blob/4a64c68d8d04a6788f1fea3d6f25471b873ee8e2/check/src/typecheck.rs#L210 ) (as an example) contains line + columns spans so the typechecker needs to know how to translate byte positions to line + column. Alternativley this conversion could be postponed until after typechecking if the typechecker stored something like `Errors<ByteSpanned<Error>>` and then that is translated to the current `Spanned<_>` type.

**Comment by brendanzab** [comment]
Yep, I think we can keep around the list of line beginning offsets then reconstruct them later as needed. Seems to be what happens in those links I posted.
